# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'user.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QWidget)
import userUiRescources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(480, 861)
        MainWindow.setStyleSheet(u"background-color: rgb(0, 33, 72);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.soundOnPushButton = QPushButton(self.centralwidget)
        self.soundOnPushButton.setObjectName(u"soundOnPushButton")
        self.soundOnPushButton.setGeometry(QRect(370, 0, 75, 81))
        icon = QIcon()
        icon.addFile(u":/pictures/uiPictrues/soundsOn.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.soundOnPushButton.setIcon(icon)
        self.soundOnPushButton.setIconSize(QSize(70, 70))
        self.soundOffPushButton = QPushButton(self.centralwidget)
        self.soundOffPushButton.setObjectName(u"soundOffPushButton")
        self.soundOffPushButton.setGeometry(QRect(370, 0, 75, 81))
        icon1 = QIcon()
        icon1.addFile(u":/pictures/uiPictrues/soundOff.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.soundOffPushButton.setIcon(icon1)
        self.soundOffPushButton.setIconSize(QSize(70, 70))
        self.takeCarPushButton = QPushButton(self.centralwidget)
        self.takeCarPushButton.setObjectName(u"takeCarPushButton")
        self.takeCarPushButton.setGeometry(QRect(10, -10, 181, 91))
        font = QFont()
        font.setPointSize(20)
        self.takeCarPushButton.setFont(font)
        self.takeCarPushButton.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.returnCarPushButton = QPushButton(self.centralwidget)
        self.returnCarPushButton.setObjectName(u"returnCarPushButton")
        self.returnCarPushButton.setGeometry(QRect(190, 0, 181, 71))
        self.returnCarPushButton.setFont(font)
        self.returnCarPushButton.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.humanLabel = QLabel(self.centralwidget)
        self.humanLabel.setObjectName(u"humanLabel")
        self.humanLabel.setGeometry(QRect(60, 140, 140, 210))
        self.humanLabel.setPixmap(QPixmap(u":/pictures/uiPictures/human.png"))
        self.humanLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.borrowerLabel = QLabel(self.centralwidget)
        self.borrowerLabel.setObjectName(u"borrowerLabel")
        self.borrowerLabel.setGeometry(QRect(70, 90, 131, 31))
        font1 = QFont()
        font1.setPointSize(18)
        self.borrowerLabel.setFont(font1)
        self.borrowerLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.carTakeLabel = QLabel(self.centralwidget)
        self.carTakeLabel.setObjectName(u"carTakeLabel")
        self.carTakeLabel.setGeometry(QRect(320, 80, 61, 31))
        self.carTakeLabel.setFont(font1)
        self.carTakeLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.carKeysLabel = QLabel(self.centralwidget)
        self.carKeysLabel.setObjectName(u"carKeysLabel")
        self.carKeysLabel.setGeometry(QRect(290, 130, 140, 210))
        self.carKeysLabel.setPixmap(QPixmap(u":/pictures/uiPictures/auto.png"))
        self.carKeysLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.clockPictureLabel = QLabel(self.centralwidget)
        self.clockPictureLabel.setObjectName(u"clockPictureLabel")
        self.clockPictureLabel.setGeometry(QRect(290, 510, 140, 140))
        self.clockPictureLabel.setPixmap(QPixmap(u":/pictures/uiPictures/clock.png"))
        self.clockPictureLabel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.keysLineEdit = QLineEdit(self.centralwidget)
        self.keysLineEdit.setObjectName(u"keysLineEdit")
        self.keysLineEdit.setGeometry(QRect(270, 350, 181, 41))
        self.keysLineEdit.setFont(font1)
        self.keysLineEdit.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.keysLineEdit.setClearButtonEnabled(True)
        self.licenseLineEdit = QLineEdit(self.centralwidget)
        self.licenseLineEdit.setObjectName(u"licenseLineEdit")
        self.licenseLineEdit.setGeometry(QRect(40, 360, 201, 41))
        self.licenseLineEdit.setFont(font1)
        self.licenseLineEdit.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.licenseLineEdit.setClearButtonEnabled(True)
        self.calenderLabel = QLabel(self.centralwidget)
        self.calenderLabel.setObjectName(u"calenderLabel")
        self.calenderLabel.setGeometry(QRect(50, 500, 171, 151))
        self.calenderLabel.setPixmap(QPixmap(u":/pictures/uiPictures/calender.png"))
        self.dateLabel = QLabel(self.centralwidget)
        self.dateLabel.setObjectName(u"dateLabel")
        self.dateLabel.setGeometry(QRect(70, 660, 111, 21))
        self.dateLabel.setFont(font1)
        self.dateLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.goBackPushButton = QPushButton(self.centralwidget)
        self.goBackPushButton.setObjectName(u"goBackPushButton")
        self.goBackPushButton.setGeometry(QRect(20, 700, 211, 91))
        self.goBackPushButton.setFont(font)
        self.goBackPushButton.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.hourLabel = QLabel(self.centralwidget)
        self.hourLabel.setObjectName(u"hourLabel")
        self.hourLabel.setGeometry(QRect(330, 670, 61, 21))
        self.hourLabel.setFont(font1)
        self.hourLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.nameLabel = QLabel(self.centralwidget)
        self.nameLabel.setObjectName(u"nameLabel")
        self.nameLabel.setGeometry(QRect(60, 410, 161, 41))
        self.nameLabel.setFont(font1)
        self.nameLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.carInfoLabel = QLabel(self.centralwidget)
        self.carInfoLabel.setObjectName(u"carInfoLabel")
        self.carInfoLabel.setGeometry(QRect(280, 410, 161, 41))
        self.carInfoLabel.setFont(font1)
        self.carInfoLabel.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.okPushButton = QPushButton(self.centralwidget)
        self.okPushButton.setObjectName(u"okPushButton")
        self.okPushButton.setGeometry(QRect(250, 700, 211, 91))
        self.okPushButton.setFont(font)
        self.okPushButton.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.keysReturnLineEdit = QLineEdit(self.centralwidget)
        self.keysReturnLineEdit.setObjectName(u"keysReturnLineEdit")
        self.keysReturnLineEdit.setGeometry(QRect(270, 350, 181, 41))
        self.keysReturnLineEdit.setFont(font1)
        self.keysReturnLineEdit.setStyleSheet(u"color: rgb(75, 188, 197);")
        self.keysReturnLineEdit.setClearButtonEnabled(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 480, 33))
        self.menubar.setStyleSheet(u"background-color: rgb(223, 32, 112);")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setStyleSheet(u"background-color: rgb(223, 32, 112);")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.soundOnPushButton.setText("")
        self.soundOffPushButton.setText("")
        self.takeCarPushButton.setText(QCoreApplication.translate("MainWindow", u"Lainaa auto", None))
        self.returnCarPushButton.setText(QCoreApplication.translate("MainWindow", u"Palauta auto", None))
        self.humanLabel.setText("")
        self.borrowerLabel.setText(QCoreApplication.translate("MainWindow", u"Lainaaja", None))
        self.carTakeLabel.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.carKeysLabel.setText("")
        self.clockPictureLabel.setText("")
        self.keysLineEdit.setText("")
        self.keysLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue avain", None))
        self.licenseLineEdit.setText("")
        self.licenseLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue ajokortti", None))
        self.calenderLabel.setText("")
        self.dateLabel.setText(QCoreApplication.translate("MainWindow", u"27.1.2025", None))
        self.goBackPushButton.setText(QCoreApplication.translate("MainWindow", u"Kumoa", None))
        self.hourLabel.setText(QCoreApplication.translate("MainWindow", u"10.09", None))
        self.nameLabel.setText(QCoreApplication.translate("MainWindow", u"Lainaajan nimi", None))
        self.carInfoLabel.setText(QCoreApplication.translate("MainWindow", u"Merkki ja Malli", None))
        self.okPushButton.setText(QCoreApplication.translate("MainWindow", u"Ok", None))
        self.keysReturnLineEdit.setText("")
        self.keysReturnLineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Lue avain", None))
    # retranslateUi

